### ISSUE TITLE
Dogfood `cml`

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/features#7]
```bash
cml ci --user-name github-actions --user-email github-actions@github.com
cml pr --skip-ci --{message,title,body}=Automated\ documentation\ update */**/README.md
```
https://github.com/iterative/features/blob/190e3c0d21aa89dc770f6905e463b53fca34efcc/.github/workflows/release.yaml#L27-L43

***

_Feel free to disregard this issue, it's just an example of the ideal `cml pr` use case and temptation was too strong to resist._

**Comment by shcheklein** [comment]
Thanks, @0x2b3bfa0 - would be cool actually to make a PR like this to the https://github.com/devcontainers/feature-template (may be not enough value though for them to install CML).

I'm happy to merge a PR and migrate this repo :)
