### ISSUE TITLE
add other tools

### ISSUE THREAD

**Issue by casperdcl** [iterative/features#9]
- [ ] TPI
- [ ] GTO
- [ ] MLEM
- [ ] CML? either as per https://github.com/iterative/setup-cml/blob/v1/src/utils.js or just download latest binary from https://github.com/iterative/cml/releases

**Comment by shcheklein** [comment]
sounds good, should we start with TPI / LEO though, first? (CML is more about CI/CD, not sure what use it would be to use in devcontainer?)

**Comment by shcheklein** [comment]
No plan to to this atm unfortunately. And it's not clear if this is needed tbh.
